//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicioCalculadora.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/serviciocalculadora2")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumaDosEnteros", ReplyAction="http://tempuri.org/IService1/SumaDosEnterosResponse")]
        int SumaDosEnteros(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumaDosEnteros", ReplyAction="http://tempuri.org/IService1/SumaDosEnterosResponse")]
        System.Threading.Tasks.Task<int> SumaDosEnterosAsync(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RestaDosEnteros", ReplyAction="http://tempuri.org/IService1/RestaDosEnterosResponse")]
        int RestaDosEnteros(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RestaDosEnteros", ReplyAction="http://tempuri.org/IService1/RestaDosEnterosResponse")]
        System.Threading.Tasks.Task<int> RestaDosEnterosAsync(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplicaDosEnteros", ReplyAction="http://tempuri.org/IService1/MultiplicaDosEnterosResponse")]
        int MultiplicaDosEnteros(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MultiplicaDosEnteros", ReplyAction="http://tempuri.org/IService1/MultiplicaDosEnterosResponse")]
        System.Threading.Tasks.Task<int> MultiplicaDosEnterosAsync(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DivideDosEnteros", ReplyAction="http://tempuri.org/IService1/DivideDosEnterosResponse")]
        double DivideDosEnteros(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DivideDosEnteros", ReplyAction="http://tempuri.org/IService1/DivideDosEnterosResponse")]
        System.Threading.Tasks.Task<double> DivideDosEnterosAsync(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClienteServicioCalculadora.ServiceReference1.CompositeType GetDataUsingDataContract(ClienteServicioCalculadora.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClienteServicioCalculadora.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClienteServicioCalculadora.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClienteServicioCalculadora.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClienteServicioCalculadora.ServiceReference1.IService1>, ClienteServicioCalculadora.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SumaDosEnteros(int valor1, int valor2) {
            return base.Channel.SumaDosEnteros(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<int> SumaDosEnterosAsync(int valor1, int valor2) {
            return base.Channel.SumaDosEnterosAsync(valor1, valor2);
        }
        
        public int RestaDosEnteros(int valor1, int valor2) {
            return base.Channel.RestaDosEnteros(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<int> RestaDosEnterosAsync(int valor1, int valor2) {
            return base.Channel.RestaDosEnterosAsync(valor1, valor2);
        }
        
        public int MultiplicaDosEnteros(int valor1, int valor2) {
            return base.Channel.MultiplicaDosEnteros(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicaDosEnterosAsync(int valor1, int valor2) {
            return base.Channel.MultiplicaDosEnterosAsync(valor1, valor2);
        }
        
        public double DivideDosEnteros(double valor1, double valor2) {
            return base.Channel.DivideDosEnteros(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<double> DivideDosEnterosAsync(double valor1, double valor2) {
            return base.Channel.DivideDosEnterosAsync(valor1, valor2);
        }
        
        public ClienteServicioCalculadora.ServiceReference1.CompositeType GetDataUsingDataContract(ClienteServicioCalculadora.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClienteServicioCalculadora.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClienteServicioCalculadora.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
